### ISSUE TITLE
Unpacking doubles does not work correctly

### ISSUE THREAD

**Issue by dannykopping** [kvz/locutus#143]
Consider the following code:

```php
<?php
	var_dump(unpack('d', pack('d', -100.876)));
?>
```

This should produce:

```php
array(1) { [1]=> float(-100.876) }
```

In JS:

```js
console.log(unpack('d', pack('d', -100.876)));
```

...produces...

```js
{ '': 100.875 }
```

Could you offer any insight?
Thanks

**Comment by kvz** [comment]
Thanks for reporting, and sorry for the long wait. This project and my motivation were in a bad spot. I recently did a lot of work to breathe new life into it (http://locutus.io/2016/05/announcing-locutus/). As part of this I'm going over all issues and PRs now. It seems this issue was resolved thanks to @Reggino, so I'm closing this : )
